-- CreateTable
CREATE TABLE "Win" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "amount" INTEGER NOT NULL,
    "week" INTEGER NOT NULL,
    "paid" BOOLEAN NOT NULL
);
